In [168]:
import pandas as pd

In [169]:
# Step 1. Loading and cleaning data
df = pd.read_csv('train.csv')
df.head()

,id,sex,bdate,has_photo,has_mobile,followers_count,graduation,education_form,relation,education_status,langs,life_main,people_main,city,last_seen,occupation_type,occupation_name,career_start,career_end,result
0,64100,2,23.4.1990,1,1.0,150.0,2012.0,Full-time,2.0,Student (Specialist),Русский;English,0,0,Kaliningrad,2020-08-19 20:47:43,university,"БФУ им. Канта (бывш. РГУ им. Канта, КГУ)",False,False,0
1,46851,2,11.4,0,1.0,92.0,2011.0,Distance Learning,4.0,Alumnus (Specialist),Русский,0,0,NaN,2020-12-25 10:31:53,university,ЛНУ (бывш. ЛНПУ) им. Тараса Шевченко,False,False,0
2,13159,2,5.10,0,1.0,62.0,2012.0,Full-time,0.0,Alumnus (Specialist),Русский,0,6,Mogilev,2020-03-06 03:37:47,university,"БРУ (бывш. МГТУ, ММИ)",False,False,0
3,59148,1,1.3.1967,0,1.0,179.0,1989.0,Full-time,4.0,PhD,Русский,False,False,Moscow,2020-10-10 18:06:27,university,Bodø Graduate School of Business,False,False,0
4,46429,2,NaN,0,1.0,74.0,2008.0,Full-time,7.0,Alumnus (Specialist),Русский,3,2,Ryazan,2020-01-03 03:34:09,university,"РГРТУ (бывш. РГРТА, РРТИ)",False,False,0

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8193 entries, 0 to 8192
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                8193 non-null   int64
 1   sex               8193 non-null   int64
 2   bdate             7025 non-null   object
 3   has_photo         8193 non-null   int64
 4   has_mobile        8193 non-null   float64
 5   followers_count   8193 non-null   float64
 6   graduation        8193 non-null   float64
 7   education_form    7585 non-null   object
 8   relation          8193 non-null   float64
 9   education_status  8193 non-null   object
 10  langs             8193 non-null   object
 11  life_main         8193 non-null   object
 12  people_main       8193 non-null   object
 13  city              7611 non-null   object
 14  last_seen         8193 non-null   object
 15  occupation_type   8000 non-null   object
 16  occupation_name   8000 non-null   object
 17  career_start      8193 non-null   object
 18  career_end        8193 non-null   object
 19  result            8193 non-null   int64
dtypes: float64(4), int64(4), object(12)
memory usage: 1.3+ MB

In [171]:
# 1. Cek JUMLAH kelas unik di setiap kolom object
kolom_object = df.select_dtypes(include=['object']).columns
print("Jumlah kelas unik per kolom:")
print(df[kolom_object].nunique())

Jumlah kelas unik per kolom:
bdate               3562
education_form         3
education_status       9
langs                397
life_main             10
people_main            8
city                 860
last_seen           8191
occupation_type        2
occupation_name     3922
career_start          50
career_end            35
dtype: int64

In [172]:
print(df['career_start'].value_counts(dropna=False).head(10))
print(df['career_end'].value_counts(dropna=False).head(10))

career_start
False    5603
2007      249
2008      240
2010      183
2011      183
2009      173
2014      155
2006      150
2013      144
2012      138
Name: count, dtype: int64
career_end
False    7471
2009       70
2016       58
2014       49
2013       47
2008       46
2017       45
2019       45
2015       44
2011       44
Name: count, dtype: int64

In [173]:
df = df.drop(columns=['career_start', 'career_end', 'last_seen', 'occupation_name', 'bdate'])

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8193 entries, 0 to 8192
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                8193 non-null   int64
 1   sex               8193 non-null   int64
 2   has_photo         8193 non-null   int64
 3   has_mobile        8193 non-null   float64
 4   followers_count   8193 non-null   float64
 5   graduation        8193 non-null   float64
 6   education_form    7585 non-null   object
 7   relation          8193 non-null   float64
 8   education_status  8193 non-null   object
 9   langs             8193 non-null   object
 10  life_main         8193 non-null   object
 11  people_main       8193 non-null   object
 12  city              7611 non-null   object
 13  occupation_type   8000 non-null   object
 14  result            8193 non-null   int64
dtypes: float64(4), int64(4), object(7)
memory usage: 960.2+ KB

In [147]:
print(df['langs'].value_counts(dropna=False).head(10))
print(df['city'].value_counts(dropna=False).head(10))

langs
Русский                       4435
False                         1913
Русский;English                611
Русский;Українська;English      89
Русский;Українська              83
Українська                      75
Русский;English;Deutsch         71
Русский;English;Français        70
English                         55
Русский;English;Українська      46
Name: count, dtype: int64
city
Moscow              1371
Saint Petersburg    1010
NaN                  582
Kyiv                 219
Yekaterinburg        162
Minsk                111
Rostov-on-Don        109
Nizhny Novgorod      108
Odessa               105
Kazan                101
Name: count, dtype: int64

In [148]:
df['langs'] = df['langs'].apply(lambda x: 1 if x == 'False' or pd.isna(x) else len(str(x).split(';')))

In [149]:
# 1. Isi NaN dengan 'Unknown' terlebih dahulu
df['city'] = df['city'].fillna('Unknown')
# 2. Ambil list 10 kota terbanyak (termasuk 'Unknown' jika dia masuk top 10)
top_10_cities = df['city'].value_counts().head(10).index
# 3. Kelompokkan sisanya menjadi 'Other'
df['city'] = df['city'].apply(lambda x: x if x in top_10_cities else 'Other')

In [150]:
print(df['langs'].value_counts(dropna=False).head(10))
print(df['city'].value_counts(dropna=False).head(10))

langs
1     6497
2      849
3      566
4      204
5       47
6       13
7        6
8        6
9        3
10       1
Name: count, dtype: int64
city
Other               4315
Moscow              1371
Saint Petersburg    1010
Unknown              582
Kyiv                 219
Yekaterinburg        162
Minsk                111
Rostov-on-Don        109
Nizhny Novgorod      108
Odessa               105
Name: count, dtype: int64

In [151]:
# One-Hot Encoding untuk kolom city, otomatis nge-drop kolom teks aslinya
df = pd.get_dummies(df, columns=['city'], dtype=int)

In [152]:
# 1. Cek JUMLAH kelas unik di setiap kolom object
kolom_object = df.select_dtypes(include=['object']).columns
print("Jumlah kelas unik per kolom:")
print(df[kolom_object].nunique())

Jumlah kelas unik per kolom:
education_form       3
education_status     9
life_main           10
people_main          8
occupation_type      2
dtype: int64

In [153]:
print(df['education_status'].value_counts(dropna=False).head(10))
print(df['life_main'].value_counts(dropna=False).head(10))

education_status
Alumnus (Specialist)       3424
Student (Specialist)       1851
Student (Bachelor's)        924
Alumnus (Bachelor's)        807
Alumnus (Master's)          476
PhD                         273
Student (Master's)          187
Undergraduate applicant     161
Candidate of Sciences        90
Name: count, dtype: int64
life_main
0        2945
False    2361
1        1103
6        1097
5         316
7         118
2          74
3          73
4          67
8          39
Name: count, dtype: int64

In [154]:
print(df['education_form'].value_counts(dropna=False).head(10))
print(df['people_main'].value_counts(dropna=False).head(10))
print(df['occupation_type'].value_counts(dropna=False).head(10))

education_form
Full-time            5847
Distance Learning    1418
NaN                   608
Part-time             320
Name: count, dtype: int64
people_main
0        2778
False    2333
2        1702
6         632
1         406
5         275
4          34
3          33
Name: count, dtype: int64
occupation_type
university    5594
work          2406
NaN            193
Name: count, dtype: int64

In [155]:
edu_mapping = {
    'Undergraduate applicant': 0,
    'Student (Bachelor\'s)': 1,
    'Alumnus (Bachelor\'s)': 2,
    'Student (Specialist)': 3,
    'Alumnus (Specialist)': 4,
    'Student (Master\'s)': 5,
    'Alumnus (Master\'s)': 6,
    'Candidate of Sciences': 7,
    'PhD': 8
}

df['education_status_encoded'] = df['education_status'].map(edu_mapping)
df = df.drop(columns=['education_status'])

In [156]:
# Ubah string/boolean 'False' atau NaN menjadi kode angka -1
df['life_main'] = df['life_main'].replace({'False': -1, False: -1}).fillna(-1).astype(int)
df['people_main'] = df['people_main'].replace({'False': -1, False: -1}).fillna(-1).astype(int)

# Karena ini kode kategori acak, pecah pake One-Hot Encoding biar KNN gak bingung
df = pd.get_dummies(df, columns=['life_main', 'people_main'], dtype=int, prefix=['life', 'people'])

In [157]:
# Isi data kosong dengan 'Unknown'
df['education_form'] = df['education_form'].fillna('Unknown')
df['occupation_type'] = df['occupation_type'].fillna('Unknown')

# One-Hot Encoding barengan!
df = pd.get_dummies(df, columns=['education_form', 'occupation_type'], dtype=int)

In [158]:
df.head(10)

,id,sex,has_photo,has_mobile,followers_count,graduation,relation,langs,result,city_Kazan,...,people_4,people_5,people_6,education_form_Distance Learning,education_form_Full-time,education_form_Part-time,education_form_Unknown,occupation_type_Unknown,occupation_type_university,occupation_type_work
0,64100,2,1,1.0,150.0,2012.0,2.0,2,0,0,...,0,0,0,0,1,0,0,0,1,0
1,46851,2,0,1.0,92.0,2011.0,4.0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,13159,2,0,1.0,62.0,2012.0,0.0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
3,59148,1,0,1.0,179.0,1989.0,4.0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
4,46429,2,0,1.0,74.0,2008.0,7.0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5,58719,1,0,1.0,142.0,2009.0,0.0,1,1,0,...,0,0,0,0,0,0,1,0,0,1
6,48095,1,0,1.0,751.0,2021.0,0.0,1,1,0,...,0,0,0,0,0,0,1,0,1,0
7,4093,2,0,1.0,112.0,2014.0,4.0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
8,63172,1,1,1.0,318.0,2012.0,4.0,1,1,0,...,0,0,0,0,1,0,0,0,0,1
9,63848,1,1,1.0,294.0,2018.0,0.0,1,1,0,...,0,0,0,1,0,0,0,0,1,0

In [159]:
# Cek kolom mana saja yang masih punya missing value (termasuk numerik)
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)